### ISSUE TITLE
Success nor failure block called Xcode 7

### ISSUE THREAD

**Issue by dflateau** [gangverk/iTunesSearch#9]
I've been having a problem with getting itunessearch with it not returning either success or failure blocks. There aren't any examples in the project, so I'm not sure if the problem was syntax or a bug, or something with Xcode 7.0.
```
                    [ItunesSearch sharedInstance].affiliateToken = affToken;
                    [ItunesSearch sharedInstance].countryCode=countryCode;
                    [[ItunesSearch sharedInstance] getTrackWithName:songTitle artist:artistName album:newAlbumName limitOrNil:@1 successHandler:^(NSArray *result) {
                        NSLog(@"result: %@", result);
                    } failureHandler:^(NSError *error) {
                        NSLog(@"error: %@", error);
                    }];
```
The URL it creates is valid, and I can manually enter that into a browser and see the json it returns. However, neither the success or failure block is executed here (result remains undefined). Any ideas would be appreciated!

**Comment by kevinrenskers** [comment]
@eightytwo?

**Comment by eightytwo** [comment]
Hey @dflateau,

Sorry for the delay, I just took at look at your issue now. I used the Example project in this repo to test out the `getTrackWithName:artist:album:limitOrNil:successHandler:failureHandler:` method. I added some test code to the `viewDidLoad:` method of the `ViewController.m` file, which you can see below.

```
- (void)viewDidLoad {
    [super viewDidLoad];

    [[ItunesSearch sharedInstance] getTrackWithName:@"Welcome to the Jungle" artist:@"Guns N Roses" album:@"Appetite for Destruction" limitOrNil:nil successHandler:^(NSArray *result) {
        NSLog(@"Success: %@", result);
    } failureHandler:^(NSError *error) {
        NSLog(@"Failure: %@", error);
    }];
}
```

The success block fired, returning the following data.
```
Success: (
        {
        artistId = 106621;
        artistName = "Guns N' Roses";
        artistViewUrl = "https://itunes.apple.com/us/artist/guns-n-roses/id106621?uo=4";
        artworkUrl100 = "http://is1.mzstatic.com/image/thumb/Features/63/9f/bc/dj.gutruaxj.jpg/100x100bb-85.jpg";
        artworkUrl30 = "http://is5.mzstatic.com/image/thumb/Features/63/9f/bc/dj.gutruaxj.jpg/30x30bb-85.jpg";
        artworkUrl60 = "http://is2.mzstatic.com/image/thumb/Features/63/9f/bc/dj.gutruaxj.jpg/60x60bb-85.jpg";
        collectionCensoredName = "Appetite for Destruction";
        collectionExplicitness = explicit;
        collectionId = 113736;
        collectionName = "Appetite for Destruction";
        collectionPrice = "9.99";
        collectionViewUrl = "https://itunes.apple.com/us/album/welcome-to-the-jungle/id113736?i=113712&uo=4";
        country = USA;
        currency = USD;
        discCount = 1;
        discNumber = 1;
        isStreamable = 1;
        kind = song;
        previewUrl = "http://a414.phobos.apple.com/us/r1000/161/Music3/v4/12/3a/fb/123afbc6-e1bc-52b7-7653-bb77ead487df/mzaf_520272822796705423.plus.aac.p.m4a";
        primaryGenreName = Rock;
        radioStationUrl = "https://itunes.apple.com/station/idra.113712";
        releaseDate = "1987-07-21T07:00:00Z";
        trackCensoredName = "Welcome to the Jungle";
        trackCount = 12;
        trackExplicitness = notExplicit;
        trackId = 113712;
        trackName = "Welcome to the Jungle";
        trackNumber = 1;
        trackPrice = "1.29";
        trackTimeMillis = 273600;
        trackViewUrl = "https://itunes.apple.com/us/album/welcome-to-the-jungle/id113736?i=113712&uo=4";
        wrapperType = track;
    }
)
```

Can you try copying my code and see if that works for you? You'll notice I didn't set an affiliate token or country code but even when I supply this information the success handler is still called.

Let me know how you go!

**Comment by dflateau** [comment]
Sorry for the *very very* late reply, but I did eventually find out what was causing the problem. Having AFNetworking (2.6) also installed with cocoapods breaks itunessearch in this way with returning no blocks. I haven't had time to investigate what exactly why it breaks it, but I thought I'd let you know.

**Comment by dflateau** [comment]
Sorry for the *very very* late reply, but yes, I can get your code to work when it's in viewDidLoad, but it doesn't work when it's called elsewhere in another method, such as when responding in a third-party action sheet method. What could I be missing?

**Comment by kevinrenskers** [comment]
I'm afraid that we can't really help you with more generic problems like that. The library works, I think you'll need to debug your problem yourself. Sorry!
